model:
  type: FQOUNet
  scaling_factor: 32
  compile: true


epochs: 500

loss:
  weights:
    pixel_l2: 1.
    phase: 0.1

data:
  batch_size: 64
  dataset_limit: 5555
  train_eval_split: 0.9
  train_drop_last: True
  random_flip: true
  noise: 0.

precision: 32

gradient_max: 100

mixed_precision: true

log:
  run_name: overfitt_fqo_unet

optimizer:
  type: AdamW
  lr: 5e-4
  weight_decay: 0.00005

scheduler:
  type: CosLRWarmup
  cycle_length: 450
  min_lr: 1e-5
  warmup_epochs: 50
  warmup_lr: 1e-5

